# Generated by Django 4.1.5 on 2023-01-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Рубрика, к которой относится статья', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_blog.categories'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Тэги, связанные со статьёй', null=True, to='app_blog.tags'),
        ),
    ]
