# Generated by Django 4.1.5 on 2023-01-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_articles_category_alter_articles_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Тэги, связанные со статьёй', to='app_blog.tags'),
        ),
    ]
