# Generated by Django 4.1.5 on 2023-01-07 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_alter_articles_author_alter_articles_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создания статьи'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата обновления (изменения) статьи'),
        ),
    ]
