# Generated by Django 4.1.5 on 2023-01-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_alter_articles_created_alter_articles_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='published',
            field=models.DateTimeField(blank=True, default=None, help_text='Дата опубликования статьи', null=True),
        ),
    ]
