# Generated by Django 4.1.5 on 2023-01-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_alter_categories_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toc',
            name='category',
        ),
        migrations.AddField(
            model_name='toc',
            name='article',
            field=models.ForeignKey(blank=True, default=None, help_text='Ссылка на статью', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_blog.articles'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL для статьи (должен быть уникальным)', max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='toc',
            name='menu_order',
            field=models.IntegerField(help_text='Указывается порядок в пределах своего уровня'),
        ),
        migrations.AlterField(
            model_name='toc',
            name='name',
            field=models.CharField(help_text='Наименование пункта оглавления', max_length=100),
        ),
        migrations.AlterField(
            model_name='toc',
            name='path',
            field=models.CharField(help_text='Составной путь для каждого из пунк-тов оглавления.', max_length=100),
        ),
        migrations.AlterField(
            model_name='toc',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL для пункта оглавления (должен быть уникальным)', max_length=250, null=True, unique=True),
        ),
    ]
