# Generated by Django 4.1.5 on 2023-01-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0009_remove_toc_category_toc_article_alter_articles_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='tag',
            field=models.ManyToManyField(blank=True, default=None, help_text='Тэги, связанные со статьёй', null=True, to='app_blog.tags'),
        ),
    ]
