# Generated by Django 4.1.5 on 2023-01-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0010_alter_articles_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='tag',
            field=models.ManyToManyField(help_text='Тэги, связанные со статьёй', to='app_blog.tags'),
        ),
    ]
