# Generated by Django 4.1.5 on 2023-02-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='articles_pics'),
        ),
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True, help_text='Описание категории', null=True),
        ),
    ]
