# Generated by Django 4.1.5 on 2023-02-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_articles_image_categories_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, default='default\\categories_default.jpg', help_text='Картинка для категории', null=True, upload_to='categories_pics'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='default\\articles_default.jpg', help_text='Картинка для статьи', null=True, upload_to='articles_pics'),
        ),
    ]
