# Generated by Django 4.1.5 on 2023-02-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_categories_image_alter_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='app_blog\\default\\articles_default.jpg', help_text='Картинка для статьи', null=True, upload_to='app_blog\\articles_pics'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, default='app_blog\\default\\categories_default.jpg', help_text='Картинка для категории', null=True, upload_to='app_blog\\categories_pics'),
        ),
    ]
