# Generated by Django 4.1.5 on 2023-02-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_alter_categories_image_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, default='app_blog\\default\\categories_default.jpg', help_text='Картинка для категории', null=True, upload_to='app_blog\\categories_pics', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(help_text='Наименование категории', max_length=50, verbose_name='Наименование'),
        ),
    ]
